# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: ecommerce-alerts
#   namespace: monitoring
# spec:
groups:
  - name: ecommerce
    rules:
      - alert: HighErrorRate
        expr: |
          sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) 
          / 
          sum(rate(http_server_requests_seconds_count[5m])) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High HTTP error rate
          description: "Error rate is {{ $value }}% for the last 5 minutes"

      - alert: SlowResponses
        expr: http_server_requests_seconds_sum{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow HTTP responses
          description: "95th percentile of response time is above 2 seconds"

      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total{container!=""} > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: "Container {{ $labels.container }} CPU usage is {{ $value }}%"
