global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: otel-collector
    static_configs:
    - targets:
      - 'collector:8888'

  - job_name: "cart-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["cart-service:8001"]
        labels:
          application: "Cart Service Application"

  - job_name: "catalog-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["catalog-service:8002"]
        labels:
          application: "Catalog Service Application"

  - job_name: "chat-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["chat-service:8003"]
        labels:
          application: "Chat Service Application"

  - job_name: "customer-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["customer-service:8004"]
        labels:
          application: "Customer Service Application"

  - job_name: "inventory-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["inventory-service:8005"]
        labels:
          application: "Inventory Service Application"

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["notification-service:8006"]
        labels:
          application: "Notification Service Application"

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["order-service:8007"]
        labels:
          application: "Order Service Application"

  - job_name: "payment-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["payment-service:8008"]
        labels:
          application: "Payment Service Application"

  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["product-service:8009"]
        labels:
          application: "Product Service Application"

  - job_name: "promotion-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["promotion-service:8010"]
        labels:
          application: "Promotion Service Application"

  - job_name: "review-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["review-service:8011"]
        labels:
          application: "Review Service Application"

  - job_name: "search-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["search-service:8012"]
        labels:
          application: "Search Service Application"

  - job_name: "shipping-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["shipping-service:8013"]
        labels:
          application: "Shipping Service Application"

  - job_name: "supplier-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["supplier-service:8014"]
        labels:
          application: "Supplier Service Application"

  - job_name: "translate-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["translate-service:8015"]
        labels:
          application: "Translate Service Application"

  - job_name: "warehouse-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["warehouse-service:8016"]
        labels:
          application: "Warehouse Service Application"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
rule_files:
  - "alert.rules"