server:
  port: 5004 # ${SERVER_PORT}
  servlet:
    context-path: /api
  shutdown: graceful
#  compression:
#    enabled: true
#    min-response-size: 1024
#  ssl:
#    key-store: classpath:keystore.p12  # Đường dẫn đến keystore
#    key-store-password: password       # Mật khẩu keystore
#    key-store-type: PKCS12             # Loại keystore
#    key-alias: tomcat                  # Alias của key

spring:
  application:
    name: congthanhapp-ecommerce-inventory-service

  lifecycle:
    timeout-per-shutdown-phase: 30s

  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET,POST,PUT,PATCH,DELETE
      allowed-headers: "*"
      allow-credentials: true

  datasource:
    url: jdbc:postgresql://localhost:5432/CongThanhApp-Ecommerce
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database: default
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/CongThanhApp-Ecommerce
      database: CongThanhApp-Ecommerce

    redis:
      port: 6379
      password: your_password_if_any
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
    schema:
      printer:
        enabled: true
    path: /graphql

  security:
    user:
      name: user # Tên người dùng mặc định
      password: password # Mật khẩu mặc định
    jwt:
      token:
        secretKey: ${JWT_SECRET_KEY}
        tokenPrefix: "Bearer "
        tokenExpirationAfterDays: 30

#  main:
#    allow-circular-references: true
#    allow-bean-definition-overriding: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

#    Cấu hình upload file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  activemq:
    packages:
      trust-all: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#  Cấu hình quốc tế hoá i18n
  messages:
    basename: messages

grpc:
  server:
    port: 9090
    in-process-name: congthanhapp-ecommerce-cart-service
    reflection-service-enabled: true

keycloak:
  realm: ecommerce-realm
  auth-server-url: http://keycloak:8080/auth
  resource: catalog-service
  bearer-only: true
  ssl-required: external
  credentials:
    secret: your-client-secret
  autodetect-bearer-only: true
  cors: true

ai:
  ollama:
    embedding:
      enabled: false
  vectorstore:
    pgvector:
      index-type: hnsw
      distance-type: cosine_distance
      dimensions: 384

congthanhapp:
  openapi:
    dev-url: http://localhost:5000
    prod-url: https://congthanhapp-api.com

springdoc:
  swagger-ui:
    tagsSorter: alpha
  enable-spring-security: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted
    refresh:
      access: unrestricted
    restart:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /admin
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

axon:
  axonserver:
    servers: localhost:8124
    enabled: true
  serializer:
    events: jackson

snowflake:
  worker-id: 1
  datacenter-id: 1

resilience4j:
  circuitbreaker:
    instances:
      rest-circuit-breaker:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      rest-api:
        max-attempts: 3
