apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promotion-service
  name: promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  strategy: {}
  template:
    metadata:

      labels:
        app: promotion-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-promotion:5432/promotion-service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: saiupadhyayula007/promotion-service:latest
          name: promotion-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: promotion-service
  name: promotion-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9191
  selector:
    app: promotion-service
status:
  loadBalancer: {}
