apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog-service
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  strategy: {}
  template:
    metadata:

      labels:
        app: catalog-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-catalog:5432/catalog-service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: saiupadhyayula007/catalog-service:latest
          name: catalog-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog-service
  name: catalog-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9191
  selector:
    app: catalog-service
status:
  loadBalancer: {}
