name: Test Environment Integration

on:
  push:
    branches: [ test ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Setup test environment
    - name: Setup Docker Compose
      run: docker-compose -f docker-compose.test.yml up -d
    
    # Run integration tests
    - name: Run Integration Tests
      run: |
        docker-compose exec -T test-runner npm run test:integration
    
    # Generate test reports
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: test-reports/