apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy: {}
  template:
    metadata:

      labels:
        app: payment-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-payment:5431/payment-service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: saiupadhyayula007/payment-service:latest
          name: payment-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9193
  selector:
    app: payment-service
status:
  loadBalancer: {}
