server:
  port: 5000
spring:
  application:
    name: congthanhapp-ecommerce-api-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/realms/Yas
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF #gitleaks:allow
            scope: openid, profile, email, roles

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cart-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CART-SERVICE
          predicates:
            - Path=/api/ecommerce/cart/**

        - id: catalog-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CATALOG-SERVICE
          predicates:
              - Path=/api/ecommerce/category/**, /api/ecommerce/brand/**, /api/ecommerce/tag/**

        - id: customer-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CUSTOMER-SERVICE
          predicates:
            - Path=/api/ecommerce/customer/**

        - id: inventory-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-INVENTORY-SERVICE
          predicates:
            - Path=/api/ecommerce/inventory/**

        - id: notification-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-NOTIFICATION-SERVICE
          predicates:
            - Path=/api/ecommerce/notification/**

        - id: order-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-ORDER-SERVICE
          predicates:
            - Path=/api/ecommerce/order/**, /api/ecommerce/checkout/**

        - id: payment-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: product-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: promotion-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PROMOTION-SERVICE
          predicates:
            - Path=/promotion/**

        - id: review-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-REVIEW-SERVICE
          predicates:
            - Path=/api/ecommerce/review/**

        - id: search-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-SEARCH-SERVICE
          predicates:
            - Path=/search/**

        - id: shipping-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-SHIPPING-SERVICE
          predicates:
            - Path=/shipping/**

        - id: supplier-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-SUPPLIER-SERVICE
          predicates:
            - Path=/supplier/**

        - id: warehouse-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-WAREHOUSE-SERVICE
          predicates:
            - Path=/warehouse/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

#logging:
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
