server:
  port: 5000

spring:
  application:
    name: congthanhapp-ecommerce-api-gateway
  main:
    web-application-type: reactive

  security:
    enable: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cart-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CART-SERVICE
          predicates:
            - Path=/api/ecommerce/cart/**

        - id: catalog-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CATALOG-SERVICE
          predicates:
            - Path=/api/ecommerce/catalog/**

        - id: inventory-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**

        - id: notification-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**

        - id: order-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-ORDER-SERVICE
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: product-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: promotion-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PROMOTION-SERVICE
          predicates:
            - Path=/promotion/**

        - id: review-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-REVIEW-SERVICE
          predicates:
            - Path=/review/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

#logging:
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
