server:
  port: 8080
spring:
  application:
    name: congthanhapp-ecommerce-api-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/realms/Yas
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF #gitleaks:allow
            scope: openid, profile, email, roles

  cloud:
    loadbalancer:
      retry:
        enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: cart-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CART-SERVICE
          predicates:
            - Path=/api/ecommerce/carts/**, /api/graphql

        - id: catalog-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CATALOG-SERVICE
          predicates:
              - Path=/api/ecommerce/categories/**, /api/ecommerce/brands/**, /api/ecommerce/tags/**, /api/ecommerce/catalog/graphql
#          filters:
#            - RewritePath=/catalog-service/(?<segment>.*), /$\\{segment}

        - id: common-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-COMMON-SERVICE
          predicates:
            - Path=/api/ecommerce/common/**

        - id: customer-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-CUSTOMER-SERVICE
          predicates:
            - Path=/api/ecommerce/customer/address/**, /api/ecommerce/customer/**, /api/ecommerce/customer/wishlist/**, /api/graphql

        - id: inventory-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-INVENTORY-SERVICE
          predicates:
            - Path=/api/ecommerce/inventory/**, /api/graphql

        - id: message-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-MESSAGE-SERVICE
          predicates:
            - Path=/api/ecommerce/message/**, /api/graphql

        - id: notification-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-NOTIFICATION-SERVICE
          predicates:
            - Path=/api/ecommerce/notifications/**, /api/graphql

        - id: order-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-ORDER-SERVICE
          predicates:
            - Path=/api/ecommerce/orders/**, /api/ecommerce/checkout/**, /api/graphql

        - id: payment-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PAYMENT-SERVICE
          predicates:
            - Path=/api/ecommerce/payment/**, /api/graphql

        - id: product-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=/api/ecommerce/products/**, /api/graphql

        - id: promotion-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-PROMOTION-SERVICE
          predicates:
            - Path=/api/ecommerce/promotions/**, /api/graphql

        - id: review-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-REVIEW-SERVICE
          predicates:
            - Path=/api/ecommerce/reviews/**, /api/graphql

        - id: search-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-SEARCH-SERVICE
          predicates:
            - Path=/api/ecommerce/search/**, /api/graphql

        - id: shipping-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-SHIPPING-SERVICE
          predicates:
            - Path=/api/ecommerce/shipping/**, /api/graphql

        - id: supplier-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-SUPPLIER-SERVICE
          predicates:
            - Path=/api/ecommerce/suppliers/**, /api/graphql

        - id: translate-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-TRANSLATE-SERVICE
          predicates:
            - Path=/api/ecommerce/translate/**, /api/graphql

        - id: warehouse-service
          uri: lb://CONGTHANHAPP-ECOMMERCE-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/ecommerce/warehouse/**, /api/graphql

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

#logging:
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
