server:
  port: 8888

spring:
  application:
    name: congthanhapp-ecommerce-config-service
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
