server:
  port: 8888

spring:
  application:
    name: congthanhapp-ecommerce-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/your-config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
