server:
  port: 5009

spring:
  application:
    name: CongThanhApp - Ecommerce - promotion-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

