server:
  port: 5009

spring:
  application:
    name: congthanhapp-ecommerce-promotion-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      default-zone: http://eureka:123456@localhost:8761/eureka
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
#    prefer-ip-address: true

