spring:
  application:
    name: congthanhapp-ecommerce-media-service

  config:
    import:
      - optional:file:./.env
      - configserver:http://localhost:8888/

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  profiles:
    active: dev