name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: |-
          echo "name=$(basename ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})" >> "$GITHUB_ENV"
          echo "version=${GITHUB_SHA:0:7}" >> "$GITHUB_ENV"

      - name: Build Docker Image
        if: ${{ env.name != 'master' }}
        run: docker build -t reh-web --target development .

      - name: Run Tests
        if: ${{ env.name != 'master' }}
        run: docker run --entrypoint yarn reh-web workspaces run lint

      # - name: Build dalemundi
      #   run: |-
      #     docker build -t 036666651253.dkr.ecr.us-east-2.amazonaws.com/dalemundi:commit-${{ env.version }} . \
      #       --build-arg NEXT_PUBLIC_FBAPPID=${{ vars.NEXT_PUBLIC_FBAPPID_DALEMUNDI }} \
      #       --build-arg NEXT_PUBLIC_GOOGLECLIENTID=${{ vars.NEXT_PUBLIC_GOOGLECLIENTID_DALEMUNDI }} \
      #       --build-arg NEXT_PUBLIC_RECAPTCHASITEKEY=${{ vars.NEXT_PUBLIC_RECAPTCHASITEKEY }} \
      #       --target release

      - name: Build Guglu
        run: |-
          docker build -t 036666651253.dkr.ecr.us-east-2.amazonaws.com/guglu:commit-${{ env.version }} . \
            --build-arg APP=guglu \
            --build-arg NEXT_PUBLIC_FBAPPID=${{ vars.NEXT_PUBLIC_FBAPPID }} \
            --build-arg NEXT_PUBLIC_GOOGLECLIENTID=${{ vars.NEXT_PUBLIC_GOOGLECLIENTID }} \
            --build-arg NEXT_PUBLIC_RECAPTCHASITEKEY=${{ vars.NEXT_PUBLIC_RECAPTCHASITEKEY }} \
            --target release

      - name: Tag Staging
        if: ${{ env.name == 'master' }}
        run: docker tag 036666651253.dkr.ecr.us-east-2.amazonaws.com/guglu:commit-${{ env.version }} 036666651253.dkr.ecr.us-east-2.amazonaws.com/guglu:staging

      - name: AWS Credentials
        if: ${{ env.name == 'master' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: "github-actions"
          aws-region: "us-east-2"
          role-duration-seconds: 900

      - name: Login to Amazon ECR
        if: ${{ env.name == 'master' }}
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Image
        if: ${{ env.name == 'master' }}
        run: |-
          docker push 036666651253.dkr.ecr.us-east-2.amazonaws.com/guglu:commit-${{ env.version }}
          docker push 036666651253.dkr.ecr.us-east-2.amazonaws.com/guglu:staging
