spring:
#  zipkin:
#    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
#  config:
#    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  application:
    name: congthanhapp-ecommerce-inventory-service
  profiles:
    active:
      - dev