spring:
  application:
    name: chatbot-service

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: true
        options:
          model: mistral
          temperature: 0.7

    openai:
      api-key: aaaaaaaaaaaaaaaa

