server:
  port: 5008 # ${SERVER_PORT}
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 1024
#  ssl:
#    key-store: classpath:keystore.p12  # Đường dẫn đến keystore
#    key-store-password: password       # Mật khẩu keystore
#    key-store-type: PKCS12             # Loại keystore
#    key-alias: tomcat                  # Alias của key

spring:
  application:
    name: congthanhapp-ecommerce-product-service

#  profiles:
#    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/CongThanhApp-Ecommerce
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver


    mysql:
      url: jdbc:mysql://localhost:3306/mydream?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: default
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mongodb:
    uri: mongodb://localhost:27017/MyDream
    database: CongThanhApp


  graphql:
    graphiql:
      enable: true
    cors:
      allowed-origins: "*"
    schema:
      printer:
        enabled: true
    path: /graphql

  security:
    user:
      name: user # Tên người dùng mặc định
      password: password # Mật khẩu mặc định
    jwt:
      token:
        secretKey: ${JWT_SECRET_KEY}
        tokenPrefix: "Bearer "
        tokenExpirationAfterDays: 30

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  mail:
    host: smtp.example.com
    port: 587
    username: myemail@example.com
    password: emailpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

#    Cấu hình upload file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET,POST,PUT,PATCH,DELETE

  data:
    redis:
      port: 6379
      password: your_password_if_any
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: congthanhapp
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#  Cấu hình quốc tế hoá i18n
  messages:
    basename: messages

  ai:
    ollama:
      embedding:
        enabled: false
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 384

  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411

congthanhapp:
  openapi:
    dev-url: http://localhost:5000
    prod-url: https://congthanhapp-api.com

springdoc:
  swagger-ui:
    tagsSorter: alpha
  enable-spring-security: true

#logging:
#  level:
#    root: INFO
##    com.yourpackage: DEBUG # Thiết lập mức log cho package cụ thể
##  org.springframework.data.mongodb.core.MongoTemplate: DEBUG
##    org.springframework.data.redis.core.RedisTemplate: DEBUG
#  file:
#    name: /var/log/myapp.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
