name: Dev Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Setup environments
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    # Build services
    - name: Build API Gateway
      run: |
        cd api-gateway
        go mod download
        go build
    
    - name: Build Auth Service
      run: |
        cd auth-service
        npm install
        npm run build
    
    # Run tests
    - name: Unit Tests API Gateway
      run: |
        cd api-gateway
        go test ./...
    
    - name: Unit Tests Auth Service
      run: |
        cd auth-service
        npm test
    
    # Create dev image
    - name: Build Docker Images
      run: |
        docker build -t dev-api-gateway ./api-gateway
        docker build -t dev-auth-service ./auth-service