version: '3.8'

services:
  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
      - post
      - media
      - notification

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - auth-db

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - user-db

  post:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - post-db

  media:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - media-storage:/app/uploads

  notification:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  user-db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  post-db:
    image: postgres:13
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  media-storage: